name: purena_lemo
description: "Purena products presentation"
publish_to: 'none'

version: 1.1.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_svg: ^2.0.9
  video_player: ^2.2.18
  select_dialog: ^2.0.1
  auto_size_text: ^3.0.0
  provider: ^6.1.1
  file_picker: ^8.0.3
  flutter_colorpicker: ^1.0.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/

  fonts:
    - family: Purena
      fonts:
        - asset: assets/fonts/Purena.otf
        - asset: assets/fonts/RobotoMono-Bold.ttf
